apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-go-basic-amqy
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-go-basic-amqy
    app.kubernetes.io/part-of: load-app-299291a0-92d6-4e6b-8f0e-ff6e5a44a3fc
  name: devfile-sample-go-basic-a0g2r
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: devfile-sample-go-basic-amqy
    weight: null
status: {}
